#!/bin/sh
if [ -f /NFR_Skin/skin.xml ]; then
  rm -rf /usr/share/enigma2/NFR_Skin
  mv /tmp/NFR_Skin /usr/share/enigma2/
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/NFR_Skin/
  mv /tmp/NFR_Skin/Extensions/Plugins/python/enigma2/lib/usr/
fi
echo "                                                          "
echo " ..NFR HD Skin  by stein17 successful installed. "
echo "                                                          "
exit 0




