#!/bin/sh
if [ -f /Blue-Line-OCT-4NFR/skin.xml ]; then
  rm -rf /usr/share/enigma2/Blue-Line-OCT-4NFR/
  mv /tmp/Blue-Line-OCT-4NFR /usr/share/enigma2/
  rm -rf /usr/lib/enigma2/python/Plugins/Extensions/BlueLineFHD/
  mv /tmp/BlueLineFHD /Extensions/Plugins/python/enigma2/lib/usr/
fi
echo "                                                          "
echo " ..BlueLineFHD Skin  by stein17 successful installed. "
echo "                                                          "
exit 0

